-- NOTE: This file is auto generated by ./sql-generator

-- PluginRepository.getForLoad
select
  "id",
  "name",
  "version",
  "wasmBytes"
from
  "plugin"
where
  "enabled" = $1

-- PluginRepository.search
select
  "plugin"."id" as "id",
  "plugin"."name" as "name",
  "plugin"."title" as "title",
  "plugin"."description" as "description",
  "plugin"."author" as "author",
  "plugin"."version" as "version",
  "plugin"."createdAt" as "createdAt",
  "plugin"."updatedAt" as "updatedAt",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          *
        from
          "plugin_method"
        where
          "plugin_method"."pluginId" = "plugin"."id"
      ) as agg
  ) as "methods"
from
  "plugin"
order by
  "plugin"."name"

-- PluginRepository.getByName
select
  "plugin"."id" as "id",
  "plugin"."name" as "name",
  "plugin"."title" as "title",
  "plugin"."description" as "description",
  "plugin"."author" as "author",
  "plugin"."version" as "version",
  "plugin"."createdAt" as "createdAt",
  "plugin"."updatedAt" as "updatedAt",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          *
        from
          "plugin_method"
        where
          "plugin_method"."pluginId" = "plugin"."id"
      ) as agg
  ) as "methods"
from
  "plugin"
where
  "plugin"."name" = $1

-- PluginRepository.get
select
  "plugin"."id" as "id",
  "plugin"."name" as "name",
  "plugin"."title" as "title",
  "plugin"."description" as "description",
  "plugin"."author" as "author",
  "plugin"."version" as "version",
  "plugin"."createdAt" as "createdAt",
  "plugin"."updatedAt" as "updatedAt",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          *
        from
          "plugin_method"
        where
          "plugin_method"."pluginId" = "plugin"."id"
      ) as agg
  ) as "methods"
from
  "plugin"
where
  "plugin"."id" = $1
